### ISSUE TITLE
FRP: Replace ts-ignore

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn-vaults-descriptions#63]
### What is your proposal 🚀
JS -> TS migration by @0xMirim was done and some `//ts-ignore` are now used in the app. They should be removed and the proper type should be used.

### What does this solve ? 🛠
Consistency and linting!

### More 🔎
*N/A*

**Comment by 0xMirim** [comment]
Ah clean up, I'm on it!  🧽 🪣 👷

The only `ts-ignore` or `ts-nocheck` I saw are in `
pages/api/protocol.tsx` though I'm sure it's just as relevant to remove as many of the `// eslint-disable` lines as possible by adding proper types.

After looking at the protocols API route I actually noticed that due to the recent depreciation of internal pages `api/protocol.tsx` (also `api/tokens.tsx` and `api/strategies.tsx`) appear to not be used at all. I did want to check here before taking action to remove these in case they are somehow still relevant and should be preserved.

Removing these API routes would be relevant to this issue though as they do contain a fair amount of the `// eslint-disable` comments.
